SELECT SHIPS.NAME, CLASSES.COUNTRY, CLASSES.NUMGUNS, SHIPS.LAUNCHED
FROM SHIPS
JOIN CLASSES on SHIPS.CLASS = CLASSES.CLASS

SELECT *
FROM CLASSES
LEFT OUTER JOIN SHIPS on CLASSES.CLASS = SHIPS.CLASS
WHERE SHIPS.NAME IS NULL;

SELECT SHIP, BATTLES.DATE
FROM OUTCOMES
JOIN BATTLES ON BATTLES.NAME = OUTCOMES.BATTLE
WHERE BATTLES.DATE LIKE '%1942%';

SELECT COUNTRY
FROM CLASSES
JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
WHERE SHIPS.NAME != (SELECT SHIP
                       FROM OUTCOMES)
GROUP BY COUNTRY;